name: P2P Chat CICD testing pipeline
on: [push, pull_request]
jobs:
    testing:
        name: Building and tesing
        runs-on: ubuntu-latest
        steps:
            - name: Install essentials
              run: sudo apt-get update && sudo apt-get install -y clang-format \
                                                                    clang-tidy \
                                                                    apt-transport-https \
                                                                    curl \
                                                                    gnupg
            - name: Fetch Bazel
              run: curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
            
            - name: Move directory
              run: sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
            
            - name: Install Bazel
              run: sudo apt update && sudo apt install bazel

            - name: Build project
              run: sudo bazel build --config=debug \
                                    --config=gcc11
                                    --config=clang-format \
                                    --config=clang-tidy \
                                    --config=ubsan \
                                    --config=asan \
                                    --config=ci
            - name: Testing
              run: sudo bazel test :all