name: P2P Chat CICD testing pipeline
on: [push, pull_request]
jobs:
    build-and-test-backend:
        name: Building and testing backend
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Install essentials
              run: |
                sudo apt-get update && sudo apt-get install -y clang-format \
                                                                    clang-tidy \
                                                                    apt-transport-https \
                                                                    curl \
                                                                    gnupg
            - name: Install Bazel
              run: |
                curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
                sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
                echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
                sudo apt-get update
                sudo apt-get install bazel

            - name: Verify Bazel Version
              run: bazel --version

            - name: Check Code Formatting (clang-format)
              run: bazel build --config=clang-format //...

            - name: Run Static Analysis (clang-tidy)
              run: bazel build --config=clang-tidy //...
      
            - name: Build Project (Debug)
              run: bazel build --config=ci --config=debug //...

            - name: Run Tests (Default)
              run: bazel test --config=ci --config=debug //...

            - name: Run Tests (Address Sanitizer)
              run: bazel test --config=ci --config=asan //...

            - name: Run Tests (Undefined Behavior Sanitizer)
              run: bazel test --config=ci --config=ubsan //...
            
            - name: Run Tests (Thread Sanitizer (TSan))
              run: bazel test --config=ci --config=tsan //...

    build-and-test-frontend:
        name: Building and testing frontend
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: 'stable'

            - name: Install dependencies
              run: flutter pub get
              working-directory: p2p_chat_client
        
            - name: Verify formatting
              run: dart format --output=none --set-exit-if-changed .
              working-directory: p2p_chat_client
        
            - name: Analyze project source
              run: flutter analyze --fatal-warnings
              working-directory: p2p_chat_client

            - name: Run tests
              run: flutter test
              working-directory: p2p_chat_client

            - name: Build apk
              run: flutter build apk
              working-directory: p2p_chat_client