name: Build and Push CI Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile.cicd' # Only run on changes to the Dockerfile
  pull_request:
    paths:
      - 'Dockerfile.cicd'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GitHub Packages/Container Registry

    steps:
      - name: Check out code
        uses: actions/checkout@v4
    
      - name: Convert repository name to lowercase
        id: repo-lower
        run: echo "repo_name=${{ github.repository }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.repo-lower.outputs.repo_name }}/cicd-image

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.cicd
          # Only push the image on merges to 'main'. On PRs, this just builds to validate.
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable Docker layer caching via GitHub Actions cache for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max